version: "3.8"

services:
    app:
        volumes:
            - ./launcher/src:/app/launcher/src
            - ./utils/:/app/utils
        container_name: react-app-prod
        image: react-app-prod
        build:
            context: .
            target: production
    nginxManager:
        image: "jc21/nginx-proxy-manager:latest"
        restart: unless-stopped
        ports:
            - "80:80"
            - "81:81"
            - "443:443"
        volumes:
            - ./data:/data
            - ./letsencrypt:/etc/letsencrypt
