version: "3.8"

services:
    app:
        volumes:
            - ./launcher/src:/app/launcher/src
            - ./utils/:/app/utils
        container_name: react-app
        image: react-app
        build:
            context: .
            target: development
        ports:
            - 3000:3000
